### ISSUE TITLE
KC-SERVICES0013:

### ISSUE THREAD

**Issue by pumajd** [raptor-group/keycloak-login-recaptcha#7]
Hi, I install the jar and get the captcha on login, but when I login, I get the next error, please help me

2020-05-15 08:44:17,322 WARN  [org.keycloak.services] (default task-15) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException
	at org.keycloak.authentication.DefaultAuthenticationFlow.processResult(DefaultAuthenticationFlow.java:243) [keycloak-services-4.8.18.Final-redhat-00001.jar:4.8.18.Final-redhat-00001]
	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:125) [keycloak-services-4.8.18.Final-redhat-00001.jar:4.8.18.Final-redhat-00001]
	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:99) [keycloak-services-4.8.18.Final-redhat-00001.jar:4.8.18.Final-redhat-00001]
	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:872) [keycloak-services-4.8.18.Final-redhat-00001.jar:4.8.18.Final-redhat-00001]
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:292) [keycloak-services-4.8.18.Final-redhat-00001.jar:4.8.18.Final-redhat-00001]
	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:263) [keycloak-services-4.8.18.Final-redhat-00001.jar:4.8.18.Final-redhat-00001]
	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:259) [keycloak-services-4.8.18.Final-redhat-00001.jar:4.8.18.Final-redhat-00001]
	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:320) [keycloak-services-4.8.18.Final-redhat-00001.jar:4.8.18.Final-redhat-00001]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_221]

**Comment by pumajd** [comment]
I pass the with success loing changing the version about, keycloakm however when I click on login, without captcha, I have the same error

**Comment by midorimide** [comment]
@pumajd 
Modify the `action` mehtod of the `RecaptchaUsernamePasswordForm` class as follows (see the `Fix KC-SERVICES0013` comment):

```java
@Override
public void action(AuthenticationFlowContext context) {
	if (logger.isDebugEnabled()) {
		logger.debug("action(AuthenticationFlowContext) - start");
	}
	MultivaluedMap<String, String> formData = context.getHttpRequest().getDecodedFormParameters();
	List<FormMessage> errors = new ArrayList<>();
	boolean success = false;
	context.getEvent().detail(Details.AUTH_METHOD, "auth_method");

	String captcha = formData.getFirst(G_RECAPTCHA_RESPONSE);
	if (!Validation.isBlank(captcha)) {
		AuthenticatorConfigModel captchaConfig = context.getAuthenticatorConfig();
		String secret = captchaConfig.getConfig().get(SITE_SECRET);

		success = validateRecaptcha(context, success, captcha, secret);
	}
	if (success) {
		super.action(context);
	} else {
		errors.add(new FormMessage(null, Messages.RECAPTCHA_FAILED));
		formData.remove(G_RECAPTCHA_RESPONSE);

		// Fix KC-SERVICES0013
		context.failure(AuthenticationFlowError.IDENTITY_PROVIDER_ERROR);
		super.action(context);

		// context.error(Errors.INVALID_REGISTRATION);
		// context.validationError(formData, errors);
		// context.excludeOtherErrors();
		return;
	}

	if (logger.isDebugEnabled()) {
		logger.debug("action(AuthenticationFlowContext) - end");
	}
}
```

You should also import AuthenticationFlowError:
```java
import org.keycloak.authentication.AuthenticationFlowError;
```

**Comment by pumajd** [comment]
Nice, thanks
